### ISSUE TITLE
great extension but can´t beat manual players on the new type of falling furni rooms

### ISSUE THREAD

**Issue by FelipePenhaa** [Julianty123/GFallingFurni#1]
Hello julianty, so this extension is fully functional but it is not able to beat manual players at the new version of falling furni rooms on the brazilian server, they use two  levers  for two people and three people , its automatic and there is also a sphere for each of these , the sphere lightens up(to indicate the  furni is landing)  after either levers are used, then the users click on the place where the furni will be landing , the sphere lightens up quicker than  the actions of the levers being pulled, the extension can not keep up with the speed of the players, so they are faster and I end up losing, can you maybe check them out and release a possible fix for this? thanks( I lose everytime even though the delay is always set to 1 the minimum), if you can make the updated extension private just for me and send it to my email I would appreciate it even more, my email: mksju3@gmail.com or discord spencer#3060

**Comment by Julianty123** [comment]
Omg, a thousand apologies, I had not seen the message. Not if that form of game still exists, I would have to take a look for a solution, regards! :)
