### ISSUE TITLE
It's a great extension, I would like to be able to disable and enable the program with a specific keyboard key.

### ISSUE THREAD

**Issue by AlanRubioChavez** [Julianty123/GFallingFurni#2]
Sometimes they put the chairs very fast and I can't turn off the program in time haha, so when I want to sit on a chair nearby, my avatar moves. If there was a key to turn the program on and off faster (with the mouse it takes me longer) or a way to not move when they put more chairs (for example: holding down a key like shift), that would be great! Thank you so much ;)

**Comment by Julianty123** [comment]
Hello, of course 😄. I've added the option for it to be "on" while you hold down Ctrl.

**Comment by AlanRubioChavez** [comment]
OMG :O, it's incredible, thank you so much Julianty, you are the best, I use most of your extensions, they are great! ;D
