### ISSUE TITLE
Unable to register football locker room furni as poison furni or specific furni

### ISSUE THREAD

**Issue by AlanRubioChavez** [Julianty123/GFallingFurni#3]
Hi Julianty!, I have another observation of crazy chairs. There is a very annoying furni that changes your clothes when you step on it, it is the football locker room furni. Lately they use it to troll and as a trap. The problem is that it won't let me register it as poison furni or specific furni. I double click it and it won't let me lol, so I can't avoid stepping on that furni. If you could fix it, I would really appreciate it. Thank you Julianty.

**Comment by Julianty123** [comment]
With the new update, it now detects both one and double click so you are able to select Football Gate furniture 💯

**Comment by AlanRubioChavez** [comment]
Amazing! Thanks Julianty ;)
