### ISSUE TITLE
When I use Specific Point Mode, the avatar moves when they place or move furniture anywhere in the room.

### ISSUE THREAD

**Issue by AlanRubioChavez** [Julianty123/GFallingFurni#4]
Hi Julianty! ;) I have had a lot of fun with this extension, it is very complete, I have won many times in crazy chairs hahaha, it is great. But now I've only had problems with Specific Point Mode, that mode is great, I like to use when we stick to the wall for safety😂. The problem is that when I set the point where I want my avatar to move and they move furniture or put furniture outside of the crazy chairs area, my avatar moves and seems to get ahead lol and then I lose (I just have that problem, everything otherwise it's perfect). So if you could please make it possible for the avatar to move to that specific point, only when they put furniture at the selected coordinates (or range of coordinates), to move only when they put furniture in the crazy chairs zone, that would be wonderful🤩 thanks julianty.

**Comment by Julianty123** [comment]
I understand the dynamics a bit, could you upload a video?

**Comment by Julianty123** [comment]
Or well, if i am correct you can use Equals coords mode instead

**Comment by AlanRubioChavez** [comment]
Exactly! It is like the Equals Coords Mode, the difference is that the avatar moves to a specific point and that more than one coordinate can be selected (when they put furniture in any of those coordinates, the avatar moves to that point). And since more coordinates would be selected, I guess there should be a button to delete the coordinates😅. Now that I think about it, it's like the combination of both modes hahaha, the new thing is that you can select more than one coordinate and the difference is that instead of the avatar sitting directly on a chair, it moves to a specific point.

So what I would like is to be able to select more than one coordinate and when they put furniture in any of those coordinates, the avatar moves to a specific point. That would be incredible! 🤩

**Comment by AlanRubioChavez** [comment]
I hope the dynamics have become clearer, if you could do that the program would be very powerful 😲, I would really appreciate it Julianty ;). The thing is that when they tell us to stick to the wall, I like to use the specific point mode because it looks more natural when I move🤣 (many tend to suspect), but when they move furniture or put furniture outside the area of crazy chairs, my avatar moves and they think I'm ahead of myself. So I would like to be able to select the coordinates where I want them to put the furniture and only when they put furniture in any of those coordinates, my avatar will move to that specific point, that way I will feel more secure😌.

**Comment by Julianty123** [comment]
❤️ Yep, i understand your point. I am just trying to make the code simple

**Comment by AlanRubioChavez** [comment]
OMG🤩, perfect 🙌, you are the best programmer. Thank you very much Julianty ;)💙

**Comment by Julianty123** [comment]
https://github.com/Julianty123/GFallingFurni/assets/22751572/f5b7a418-d43c-41a6-9774-1415aa439344

This should be the way to configure the extension. I think the extension is already complete for the purpose (if I add more features I will break it for sure and I don't want that hahaha my head is going to explode), I won't make any more updates, maybe one last one to organize the game modes in a table

**Comment by AlanRubioChavez** [comment]
Woooow perfect 😱, I can't believe it, that was the best update of this extension, it's so epic! 🔥🔥🔥 Thank you very much for everything Julianty, great video ;)💙. Don't worry, that was the only problem I was missing. Now the extension is very invulnerable 💯 🤩. And by the way, I already watched your youtube videos ;D I loved that extension to play Jason, it's another one of my favorite games haha, it's amazing.
