### ISSUE TITLE
There is a small detail, if you could add to it that would be great.

### ISSUE THREAD

**Issue by AlanRubioChavez** [Julianty123/GFallingFurni#5]
Hello again Julianty 💙, I wanted to ask you one last thing, I hope it's not too much trouble haha (if you won't make any more updates, no problem 🙁). You could also add an option in the equals coords mode so that the avatar follows the furni, the same as before (so we could select if we want it to move to a specific point or if we want it to move directly to the furni), with that it would be complete and I won't ask you for anything else, please 🙏🏻.

**Comment by Julianty123** [comment]
https://github.com/Julianty123/GFallingFurni/assets/22751572/1f9d8e77-23d0-4955-8e2a-4502060e8865

Sure but wait, it would be like this? it would only apply one coordinate for a single furni,

**Comment by AlanRubioChavez** [comment]
Exact! like this 🤩 but when putting a furni in any of the selected coordinates, the avatar follows the furni. You could do that? The point is that I plan to use it when I have to make a square with another person (sometimes they suspect and want to troll me), so I would select all the coordinates in the middle 🤣😂. So if they try to troll me and put banzais or furnis elsewhere, my avatar wouldn't move hehe, and when they put the furni only in any of those coordinates, the avatar will follow the furni ;) (that way the avatar would follow the furni in the middle and to the sides of the square). 

Normally, I could make it so that only when they place the furni in the middle of the square, the avatar moves in the middle. But the problem is that they can also put it on the sides 😕.

**Comment by Julianty123** [comment]
Ummm I don't know brother, I think that would solve with the new idea I have (create a table to organize the information) 🤔 I'll see what I can do :)

**Comment by AlanRubioChavez** [comment]
OMG😲, thank you so much brother🙏🏻, if you could solve that, that would be great😱💙
